# serverless.yml

service: nshm-tosh-api

plugins:
  - serverless-python-requirements
  - serverless-wsgi

package:
  include:
    - api/**
    - graphql_api/**
custom:
  wsgi:
    app: graphql_api.api.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-2

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

