name: deploy-aws-lambda-test

on:
  push:
    branches:
      - deploy-test

jobs:
  call-test-workflow:
    #https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
    uses: ./.github/workflows/run-tests.yaml

  deploy:
    needs: call-test-workflow
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Verify NPM
        run: npm doctor

      - name: List packages
        run: npm ls	

      - name: sls 1
        run: npm run-script requirements_1

      - name: sls 2
        run: npm run-script requirements_2

      - name: sls 3
        run: npm run-script dummy_pkg

      - name: fail now - until requirements are sorted
        run: serverless --help

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_TOSHI_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_TOSHI_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Serverless Deploy ....
        run: npm run-script deploy
        env:
          STAGE: "test"
